services:
  postgres:
    container_name: postgres_con
    image: postgres
    environment:
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: PASSWORD
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      microservice-net:
    restart: unless-stopped

  mongodb:
    container_name: mongo_con
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ADMIN
      MONGO_INITDB_ROOT_PASSWORD: ADMIN

  mongo-express:
    container_name: mongo_express_con
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ADMIN
        ME_CONFIG_MONGODB_ADMINPASSWORD: ADMIN
        ME_CONFIG_MONGODB_SERVER: mongodb

  mail-dev:
    container_name: mail_dev_con
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
networks:
  microservice-net:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  mongo: